# Generated by Django 6.0.2 on 2026-03-01 12:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0008_car_autoteka_alter_car_power_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Токен подтверждения почты')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='E-MAIL пользователя')),
                ('telephone_number', models.CharField(max_length=15, verbose_name='Номер телефона клиента')),
                ('type_request', models.CharField(choices=[('autoteka', 'Автотека'), ('contact_us', 'Связаться с нами'), ('contact_car', 'Связаться по автомобилю')], verbose_name='Тип заявки')),
                ('status', models.CharField(choices=[('wait_email_CONFIRMATION', 'Ждет потверждения E-mail'), ('email_confirmed', 'E-mail подтвержден'), ('work', 'В работе'), ('complete', 'Отработано')], verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('expires_at', models.DateTimeField(verbose_name='Дата окончания срока токена')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения заявки')),
                ('complete_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения заявки')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиента',
                'indexes': [models.Index(fields=['status', 'expires_at'], name='contacts_re_status_8c4ca1_idx'), models.Index(fields=['token'], name='contacts_re_token_6cf371_idx')],
            },
        ),
    ]
