# Generated by Django 6.0.2 on 2026-03-01 16:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcontact',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен подтверждения почты'),
        ),
    ]
