# Generated by Django 6.0.1 on 2026-02-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('feedback', models.TextField(verbose_name='Отзыв пользователя')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ компании')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/homepage_image/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Описание картинки')),
            ],
        ),
    ]
