# Generated by Django 6.0.2 on 2026-02-20 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('feedback', models.TextField(null=True, verbose_name='Отзыв пользователя')),
                ('answer', models.TextField(null=True, verbose_name='Ответ компании')),
                ('score', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('item_object', models.CharField(max_length=250, null=True, verbose_name='Объект оценки')),
                ('date_create', models.DateTimeField(verbose_name='Дата добавления отзыва')),
                ('avatar', models.URLField(null=True, verbose_name='Ссылка на аватар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/homepage_image/')),
                ('order_image', models.PositiveIntegerField(default=0, verbose_name='Порядок картинки')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Описание картинки')),
            ],
            options={
                'verbose_name': 'Картинка стартовой страницы',
                'verbose_name_plural': 'Картинки для стратовой страницы',
                'ordering': ['order_image'],
            },
        ),
    ]
