# Generated by Django 6.0.1 on 2026-02-03 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageimage',
            options={'ordering': ['order_image'], 'verbose_name': 'Картинка стартовой страницы', 'verbose_name_plural': 'Картинки для стратовой страницы'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления отзыва'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='order_image',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок картинки'),
        ),
    ]
