# Generated by Django 6.0.2 on 2026-02-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_avatars/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
