# Generated by Django 6.0.1 on 2026-02-04 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_homepageimage_options_feedback_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
