# Generated by Django 6.0.2 on 2026-02-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_feedback_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='feedback_avatars/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
