# Generated by Django 6.0.1 on 2026-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_feedback_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['date_create']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_object',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Объект оценки'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата добавления отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Отзыв пользователя'),
        ),
    ]
