# Generated by Django 6.0.1 on 2026-02-04 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_feedback_options_alter_feedback_item_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.TextField(null=True, verbose_name='Ответ компании'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(null=True, verbose_name='Отзыв пользователя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='item_object',
            field=models.CharField(max_length=250, null=True, verbose_name='Объект оценки'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
