# Generated by Django 6.0.1 on 2026-02-02 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Наименование категории')),
                ('image', models.ImageField(upload_to='uploads/category_image/')),
                ('slug', models.SlugField(max_length=25, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория автомобиля',
                'verbose_name_plural': 'Категория автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('car_model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year_release', models.DateField(verbose_name='Год выпуска')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('hydrogen', 'Водород'), ('lpg', 'СНГ (пропан-бутан)')], default='gasoline', max_length=10, verbose_name='Тип топлива')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, unique=True, verbose_name='Slug')),
                ('is_special_offer', models.BooleanField(default=False, verbose_name='Специальное предложение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auto_store.carcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/car_image/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Описание картинки')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='auto_store.car')),
            ],
            options={
                'verbose_name': 'Фотография автомобиля',
                'verbose_name_plural': 'Фотографии автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarComfortParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Параметр')),
                ('value', models.TextField(verbose_name='Значение')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_comfort_parameter', to='auto_store.car')),
            ],
            options={
                'verbose_name': 'Параметр комфорта',
                'verbose_name_plural': 'Параметры комфорта',
                'ordering': ['key'],
                'unique_together': {('car', 'key')},
            },
        ),
        migrations.CreateModel(
            name='CarParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Параметр')),
                ('value', models.TextField(verbose_name='Значение')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='another_parameter', to='auto_store.car')),
            ],
            options={
                'verbose_name': 'Параметр автомобиля',
                'verbose_name_plural': 'Параметры автомобиля',
                'ordering': ['key'],
                'unique_together': {('car', 'key')},
            },
        ),
    ]
