# Generated by Django 6.0.1 on 2026-02-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['order_image'], 'verbose_name': 'Фотография автомобиля', 'verbose_name_plural': 'Фотографии автомобиля'},
        ),
        migrations.AddField(
            model_name='carimage',
            name='order_image',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок картинки'),
        ),
    ]
