# Generated by Django 6.0.1 on 2026-02-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0002_alter_carimage_options_carimage_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость автомобиля в рублях'),
        ),
    ]
