# Generated by Django 6.0.1 on 2026-02-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0003_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Машина продана'),
        ),
    ]
