# Generated by Django 6.0.1 on 2026-02-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0004_car_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='sale',
            new_name='sold',
        ),
    ]
