# Generated by Django 6.0.1 on 2026-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0005_rename_sale_car_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_is_special_offer',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата когда автомобиль стал специальным предложением'),
        ),
    ]
