# Generated by Django 6.0.1 on 2026-02-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0006_car_date_is_special_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcategory',
            options={'ordering': ['order_category'], 'verbose_name': 'Категория автомобиля', 'verbose_name_plural': 'Категория автомобилей'},
        ),
        migrations.AddField(
            model_name='carcategory',
            name='order_category',
            field=models.PositiveIntegerField(default=1, verbose_name='Сортировка категорий'),
            preserve_default=False,
        ),
    ]
