# Generated by Django 6.0.1 on 2026-02-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0007_alter_carcategory_options_carcategory_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_in_caregory', to='auto_store.carcategory', verbose_name='Категория'),
        ),
    ]
