# Generated by Django 6.0.1 on 2026-02-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0008_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_in_category', to='auto_store.carcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=25, unique=True, verbose_name='Slug'),
        ),
    ]
