# Generated by Django 6.0.1 on 2026-02-07 21:47

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0009_alter_car_category_alter_carcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='deskription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание автомобиля'),
        ),
        migrations.AlterField(
            model_name='carcomfortparameter',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comfort_parameters', to='auto_store.car'),
        ),
        migrations.AlterField(
            model_name='carparameter',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='auto_store.car'),
        ),
    ]
