# Generated by Django 6.0.1 on 2026-02-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0010_car_deskription_alter_carcomfortparameter_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='deskription',
            new_name='desсription',
        ),
    ]
