# Generated by Django 6.0.1 on 2026-02-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0011_rename_deskription_car_desсription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='desсription',
            new_name='description',
        ),
    ]
