# Generated by Django 6.0.2 on 2026-02-21 14:45

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тип автомобиля: Легковой, Грузовой и т.д.', max_length=30, unique=True, verbose_name='Наименование категории')),
                ('image', models.ImageField(help_text='Иконка категории (рекомендуемый размер 64х64 px)', upload_to='uploads/category_image/')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=25, unique=True, verbose_name='Slug')),
                ('order_category', models.PositiveIntegerField(verbose_name='Порядок категории в выдаче')),
            ],
            options={
                'verbose_name': 'Категория автомобиля',
                'verbose_name_plural': 'Категория автомобилей',
                'ordering': ['order_category'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, help_text='Укажите бренд, выпускающий автомобиль', max_length=50, verbose_name='Бренд')),
                ('model', models.CharField(help_text='Укажите модель автомобиля', max_length=50, verbose_name='Модель')),
                ('year_release', models.PositiveIntegerField(help_text='Укажите год выпуска автомобиля', validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2027)], verbose_name='Год выпуска')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('mileage', models.PositiveIntegerField(db_index=True, help_text='Укажите пробег автомобиля в километрах', verbose_name='Пробег')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('hydrogen', 'Водород'), ('lpg', 'СНГ (пропан-бутан)')], default='gasoline', help_text='Выберите тип топлива, если бензин - оставьте пустым', max_length=10, verbose_name='Тип топлива')),
                ('power_hp', models.PositiveIntegerField(blank=True, help_text='Укажите мощность автомобиля в л.с или кВт/ч', null=True, verbose_name='Мощность автомобиля')),
                ('color', models.CharField(blank=True, help_text='Укажите цвет кузова автомобиля', max_length=30, verbose_name='Цвет кузова')),
                ('price', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Стоимость автомобиля в рублях')),
                ('sold', models.BooleanField(default=False, help_text='Укажите, продана ли машина', verbose_name='Машина продана')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, unique=True, verbose_name='Slug')),
                ('is_special_offer', models.BooleanField(default=False, help_text='Является ли автомобиль специальным предложением', verbose_name='Специальное предложение')),
                ('date_is_special_offer', models.DateTimeField(blank=True, null=True, verbose_name='Дата, когда автомобиль стал специальным предложением')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Напишите описание автомобиля', null=True, verbose_name='Описание автомобиля')),
                ('category', models.ForeignKey(help_text='Выберите категорию автомобиля', on_delete=django.db.models.deletion.CASCADE, related_name='cars_in_category', to='cars.carcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
