# Generated by Django 6.0.2 on 2026-02-21 22:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Прикрепите изображение автомобиля (макс. 15мб)', upload_to='uploads/car_image/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Разрешены только файлы изображений: JPG, JPEG, PNG, WEBP')], verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, help_text='Заглушка, если картинка не загрузится', max_length=200, verbose_name='Описание картинки')),
                ('order_image', models.PositiveIntegerField(default=0, verbose_name='Порядок картинки')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Фотография автомобиля',
                'verbose_name_plural': 'Фотографии автомобиля',
                'ordering': ['order_image'],
            },
        ),
    ]
