# Generated by Django 6.0.2 on 2026-02-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_parameter', models.CharField(choices=[('comfort', 'Комфорт'), ('technical', 'Технический')], default='technical', help_text='Выберите к какому типу относится параметр', max_length=15, verbose_name='Тип параметра')),
                ('key', models.CharField(help_text='Укажите название параметра', max_length=200, verbose_name='Параметр')),
                ('value', models.CharField(help_text='Укажите значение для параметра', max_length=50, verbose_name='Значение')),
                ('uom', models.CharField(blank=True, help_text='Укажите систему исчисления параметра (например: шт.; л.с. и т.д.)', max_length=15, null=True, verbose_name='Система исчисления')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='cars.car')),
            ],
            options={
                'verbose_name': 'Параметр автомобиля',
                'verbose_name_plural': 'Параметры автомобиля',
                'ordering': ['key'],
                'unique_together': {('car', 'key')},
            },
        ),
    ]
