# Generated by Django 6.0.2 on 2026-02-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='wheel_position',
            field=models.CharField(choices=[('left', 'Левый'), ('right', 'Правый'), ('center', 'Центр')], default='left', help_text='Выберите положение руля', max_length=15, verbose_name='Положение руля'),
        ),
    ]
