# Generated by Django 6.0.2 on 2026-02-22 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_wheel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_body',
            field=models.TextField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('universal', 'Универсал'), ('coupe', 'Купе'), ('cabriolet', 'Кабриолет'), ('roadster', 'Родстер'), ('suv', 'Внедорожник'), ('crossover', 'Кроссовер'), ('off_road', 'Внедорожник (полноразмерный)'), ('minivan', 'Минивэн'), ('van', 'Микроавтобус'), ('minibus', 'Микроавтобус (до 9 мест)'), ('pickup', 'Пикап'), ('truck', 'Грузовик'), ('van_commercial', 'Фургон'), ('sport', 'Спорткар'), ('gt', 'Гран Туризмо'), ('targa', 'Тарга'), ('electric', 'Электромобиль'), ('cross_coupe', 'Кросс-купе'), ('liftback', 'Лифтбек'), ('fastback', 'Фастбек'), ('classic', 'Классический'), ('retro', 'Ретро'), ('limousine', 'Лимузин'), ('convertible', 'Кабриолет (мягкий верх)'), ('wagon', 'Универсал (американский)'), ('compact', 'Компактный'), ('subcompact', 'Субкомпактный'), ('microcar', 'Микрокар')], default='sedan', help_text='Выберите тип кузова автомобиля', max_length=40, verbose_name='Тип кузова автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.FloatField(blank=True, help_text='Укажите объем двигателя', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Объем двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='type_transmission',
            field=models.TextField(choices=[('at', 'Автомат'), ('amt', 'Робот'), ('mt', 'Механик'), ('cvt', 'Вариатор')], default='mt', help_text='Выберите тип коробки передач', max_length=20, verbose_name='Коробка передач'),
        ),
    ]
