# Generated by Django 6.0.2 on 2026-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_car_body_car_engine_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type_transmission',
            field=models.TextField(choices=[('at', 'Автомат'), ('amt', 'Робот'), ('mt', 'Механика'), ('cvt', 'Вариатор')], default='mt', help_text='Выберите тип коробки передач', max_length=20, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='carparameter',
            name='type_parameter',
            field=models.CharField(choices=[('comfort', 'Комфорт'), ('technical', 'Технический'), ('safety', 'Безопасность')], default='technical', help_text='Выберите к какому типу относится параметр', max_length=15, verbose_name='Тип параметра'),
        ),
    ]
