# Generated by Django 6.0.2 on 2026-02-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_type_transmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='wheel_position',
            field=models.CharField(choices=[('left', 'Левый'), ('right', 'Правый'), ('center', 'Центральный')], default='left', help_text='Выберите положение руля', max_length=15, verbose_name='Положение руля'),
        ),
    ]
