# Generated by Django 6.0.2 on 2026-03-01 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_wheel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='autoteka',
            field=models.FileField(blank=True, help_text='Прикрепите автотеку автомобиля', null=True, upload_to='autoteka/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator('pdf', 'Разрешены только PDF документы')], verbose_name='Файл автотеки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_hp',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите мощность автомобиля в л.с', null=True, verbose_name='Мощность автомобиля'),
        ),
    ]
