# Generated by Django 6.0.2 on 2026-03-14 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_autoteka_alter_car_power_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='autoteka',
            field=models.FileField(blank=True, help_text='Прикрепите автотеку автомобиля', null=True, upload_to='autoteka/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Разрешены только PDF документы')], verbose_name='Файл автотеки'),
        ),
    ]
